### ISSUE TITLE
fromPath and toPath are not being called when param is number like string/number

### ISSUE THREAD

**Issue by pokusew** [faceyspacey/redux-first-router#41] opened 2017-07-12 20:19 UTC
Hi @faceyspacey,

the **fromPath function is not being called when pathSegment looks like a number string**.

```javascript
const routesMap = {
	EVENT: {
		path: '/event/:eventId/',
		fromPath: (pathSegment, key) => {
			console.warn(pathSegment, key);
			return pathSegment;
		},
		toPath: (value, key) => {
			console.warn(value, key);
			return value;
		},
	},
};
```
When **matching path like `/event/3/`**, fromPath function **is not called** and eventId is **automatically converted to number**, and there is currently **no way how to prevent this** (as far as I know).

Similarly, toPath function is **not** being called, when a number is passed in.

I believe, that this is **not the right behaviour**. When I define fromPath/toPath, I want to have a full control over the process creating value from pathSegment and vice versa.

I think, that if fromPath/toPath are defined, **only these** should be called skipping auto convert mechanism (here https://github.com/faceyspacey/redux-first-router/blob/master/src/pure-utils/pathToAction.js#L45, and https://github.com/faceyspacey/redux-first-router/blob/master/src/pure-utils/actionToPath.js#L30, it should check if fromPath/toPath is defined as a first step, if then call it and return).

**Additionally**, it may be useful to add an **option to enable/disable the number auto conversion** when matching. Also I have found **no mention about auto conversion of numbers in the docs**, it might be good to add it there.

What do you think? Could we improve the implementation of fromPath/toPath as I wrote above?

**Lastly, I would like to thank you for your library.** It is really great! It saves me a lot of headaches. The idea of using actions this way without having to worry about url in the app is just amazing!

Thanks for your answer.

**Comment by faceyspacey** [comment] 2017-07-12 20:21
Thanks. So if those functions are provided we should call the function even for numbers. Agreed. I'm open to a PR. It's super simple in this case since u only need to work with 2 pure functions.

**Comment by faceyspacey** [comment] 2017-07-12 20:23
Let's not worry about autoconversion having an option to turn it off for now. U can just use the pending new versions of these functions that has full access.

**Comment by faceyspacey** [comment] 2017-08-19 16:07
I'm closing this. If and when there is a 2.0 I'll change it, but for now it's not worth a 2.0 over this one breaking change.

**Closed by faceyspacey** 2017-08-19 16:07 UTC

**Comment by stevemao** [comment] 2017-10-16 03:04
What's the status of this? Is there any PR open for this? At the meanwhile it might be worth to document this behaviour.

**Comment by carleryd** [comment] 2018-03-01 10:49
I'm experiencing the same issue where I have a route with
/variable/0123
and the 0 is significant so I want it to remain a string.

**Comment by hedgepigdaniel** [comment] 2018-03-01 21:42
Would be good if the automatic number parsing was not the default option. It has introduced bugs for us when user generated strings happen to also be numbers. I think if the user wants to get a number out of the params it should be on them to specify that or decode it.

**Comment by carleryd** [comment] 2018-03-01 22:06
Agree @hedgepigdaniel
Ill do a PR for this since I just did that in my fork.

**Comment by faceyspacey** [comment] 2018-03-01 22:34
it's already handled in Rudy, which will be out soon. a PR can't be done here as it will break existing apps that depend on it. feel free to fork and use that for now.

**Comment by dawnmist** [comment] 2018-09-25 04:39
Just as an addition to this issue (since it has the same root cause) - fromPath is only called if val is a string. So if a path segment is optional (e.g. a segment value of '' or 'list' were meant to be the same tab within a component page, but the segment of 'edit' is another tab within that particular component page) it is not possible to use fromPath to initialize a default segment value for the empty case so that the payload value isn't left as undefined. I don't really want to create a new action type solely to represent the empty case, and it's a lot easier to be able to simply initialize the empty value/validate the segment value once and then use the payload's value instead of having to test for "if it was defined" everywhere. I've been using the old @rudy branch from npm, which still contains this issue in `pure-utils/pathToAction.js`.

**Comment by ScriptedAlchemy** [comment] 2018-09-25 07:12
I have a PR open with a handful of fixes. Can you try that branch?

**Comment by dawnmist** [comment] 2018-09-25 11:04
@ScriptedAlchemy The rudy update one? That still checks that the segment was a string, and if not it does not call fromPath. This means that when the segment is empty, fromPath is not invoked.
https://github.com/faceyspacey/redux-first-router/blob/1f984eaa8e366c4d412a89397377da7c6ad4fb01/src/pure-utils/pathToAction.js#L56-L73

An empty segment fails the `if (typeof val === 'string')` test, so fromPath/the rest of the logic is never invoked.

It does however mean that _if_ someone defines a fromPath function and the segment value is populated, the fromPath function will be called rather than auto-converting to a number.

**Comment by hedgepigdaniel** [comment] 2018-09-27 23:35
@dawnmist good point... have you worked out under what circumstances that happens? Because it seems like at least most of the time numbers come out of the match as strings (hence the code that converts them to numbers)

**Comment by dawnmist** [comment] 2018-09-28 06:05
Having a look at it - I think my problem was more that when the segment is undefined (i.e. it was an optional segment) it fails the test, and there is then no way possible to initialize it to anything because fromPath isn't called.

If the lines were changed to:
```javascript
const payload = (keys || []).reduce((payload, key, index) => { 
   let val = match && match[index + 1] // item at index 0 is the overall match, whereas those after correspond to the key's index 
  
   if (fromPath) { 
     val = fromPath && fromPath(val, key.name) 
   } 
   else if (typeof val === 'string') { 
     if (isNumber(val)) { 
       val = parseFloat(val) 
     } 
     else if (capitalizedWords) { 
       val = val.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase()) // 'my-category' -> 'My Category' 
     } 
   } 
  
   payload[key.name] = val 
   return payload 
 }, {})
```
it should work for the optional case as well. The only issue is that when writing a fromPath function the user needs to be aware that if there is an optional segment in their path the value given to them in fromPath for that key may be undefined.
