### ISSUE TITLE
Wait for thunk to finish before transition

### ISSUE THREAD

**Issue by testerez** [faceyspacey/redux-first-router#104] opened 2017-09-11 04:39 UTC
Hello, In the browser, I'd like to fetch data for the requested page before actually performing the transition.
Is there a simple way to achieve this with `redux-first-router`?

**Comment by faceyspacey** [comment] 2017-09-11 10:19
Hey @testerez! That's basically a duplicate of this issue:

https://github.com/faceyspacey/redux-first-router/issues/96

Check it out and let me know your thoughts. ..But basically you gotta use `onBeforeChange`. In that issue I describe the idiomatic way to do it in userland. However, `onBeforeChange` doesn't yet support promises, i.e it's not async. But it will in just a few more days. 

In short, I'm working on your use-case. Many people have asked this. Keep a look out a the top of the repo. The final solution for this general use case is coming soon.

**Closed by faceyspacey** 2017-09-11 10:19 UTC

**Comment by testerez** [comment] 2017-09-11 13:13
It's nice to see that this use case is taken care of! There is a part I'm still not clear about tho:
If I want to fetch before transitioning, it means that I have to keep pageA displayed while executing the thunk for pageB. But when should the location state actually change?
You can't change it before calling thunkB because pageA could rely on it. But you need it changed so thunkB can access location params.
What I was thinking about is that thunk could take the target location state as an an additional param. Does it make sense to you?

**Comment by faceyspacey** [comment] 2017-09-11 20:19
Check all the updates at the top of the readme. There's now a third arg with the action. It's not all that is in the location state but it's usually enough.

**Comment by testerez** [comment] 2017-09-11 20:31
Nice 👍  
With that, will it be possible to determine if it's a back navigation for example?
I'll give it a try soon...

**Comment by faceyspacey** [comment] 2017-09-11 21:01
in the browser u cant currently detect if it's back. only back/next by kind === 'pop'. memory history on RN is smarter. 

but na, it's a more bare action. the idea u mentioned about faking the location state, etc, have been considered. we may do more of that, but for now we needed to ship something.

**Comment by testerez** [comment] 2017-09-11 21:11
'pop' is ok for my use case. But I would also need this information to be available in the thunk args.
Basically, I think that most of the time you want to re-fetch data when you access a new page so the content is fresh. I it's a pop (back or next) you want the transition to be instant and it's expected to find the data as you leaved it.
