### ISSUE TITLE
flow types imported from library are all 'any'

### ISSUE THREAD

**Issue by petegleeson** [faceyspacey/redux-first-router#115] opened 2017-09-19 06:59 UTC
Hello

I am trying to import flow types from your library for use in my application. Unfortunately, they appear to be all 'any'. I have this simple example:

```js
/* @flow */
import type { LocationState, NavigationAction } from 'redux-first-router';

const location: LocationState = {
    foo: 'bar',
    car: 1,
};
```

Running `flow` I see `No errors!` and no complaints from my editor (vscode). If I hover over the types, vscode tells me they are 'any'.

I have had a dig around in node_modules/redux-first-router/dist and the `flow-types.js` file is empty. There are type definitions in `flow-types.js.flow` and `index.js.flow`. 

I am have tried v0.0.16-next and v1.9.19 with no success. I am on flow version 0.52.0.

**Comment by faceyspacey** [comment] 2017-09-19 07:31
flow-types.js is supposed to have them stripped. and vs-code (and flow from the cli) are supposed to know to look in files with the same names ending in the `.flow` extension, which you do have. 

I can't quite tell you what the issue is.

**Comment by petegleeson** [comment] 2017-09-20 02:00
Am I importing the types in the right way? 

I have put together a simple repo that illustrates the problem. Could you please tell me what behaviour you get?

https://github.com/petegleeson/redux-first-router-flow

**Comment by faceyspacey** [comment] 2017-09-22 12:12
truth is I dont know. i just git cloned your repo. and it's not working as it should. i copy/pasted the entire redux-first-router/dist/flow-types.js.flow file to the top of the file and the flow types began to work correctly. 

I've been doing a lot of open source package work lately, and when I do implement the packages in things like demos and boilerplates, I dont in fact use Flow. So this is a major blindspot for me. This is not good. But my best guess is it's not an issue with RFR, but with Flow. The way it's supposed to work is you put .flow files next to your regular files and types will be interpreted from there. We need to get to the bottom of this. Can you look into other packages using flow in this way, and see if they are working??

That said, putting the definitions in the flow-typed library would probably solve it, and may in fact be preferable for several reasons.

Any help to bring this together is much appreciated.

**Comment by faceyspacey** [comment] 2017-09-26 08:18
I'm gonna close this as a matter of house keeping. basically we need to put the flow definitions in the flowtyped library. I'll do this when the flow-types are finalized for the upcoming Rudy renaming. But if you want to do this now, feel free to take `src/flow-types.js` and put them there, and then I'll update them.

**Closed by faceyspacey** 2017-09-26 08:18 UTC

**Comment by petegleeson** [comment] 2017-09-30 06:54
Hey mate, I think I have fixed this problem. The `// @flow` annotation was missing in `index.js`. I tested my changes with the repo above and the types are being imported correctly.

**Comment by faceyspacey** [comment] 2017-09-30 07:04
thanks excellent! Excellent catch!!
