### ISSUE TITLE
addRoutes action does not re-evaluate current location

### ISSUE THREAD

**Issue by woochi** [faceyspacey/redux-first-router#283] opened 2018-09-08 13:19 UTC
When dynamically loading new routes via the `addRoutes` (available in the `redux-first-router@next` release) action the current location is not re-evaluated with the new route information. This means, that in a situation where the user e.g. refreshes the browser in a dynamically loaded route (or opens a new window which points to a dynamically loaded route), the current location is initialized as `NOT_FOUND` and stays as such even when the new routes have been dynamically loaded and added.

An example code scenario using [React Universal Component](https://github.com/faceyspacey/react-universal-component) to dynamically load a new component module and mount new routes:

```
// dynamic-component.js
// ==================================

export const routes = {
  DYNAMIC_ROUTE: '/dynamic_route'
};

const DynamicComponent = connect(state => ({
  location: state.location
}))((props) => <div>{props.location.type}</div>)

export default DynamicComponent

// app.js
// ==================================

const DynamicComponent = universal(() => import('./dynamic-component'), {
  onLoad: async (module) => {
    await store.dispatch(addRoutes(module.routes));
  }
});

...

<Provider store={store}>
  </DynamicComponent>
</Provider>
```

Refreshing the browser at `/dynamic_route` will render the location `NOT_FOUND` in the `DynamicComponent`. Only by navigating to some other route and then back to the `/dynamic_route` will the correct `DYNAMIC_ROUTE` be rendered in the component.

This can currently be worked around by dispatching a navigation action `{ type: 'DYNAMIC_ROUTE' }` after new routes have been added but this means that the app will always navigate to some specific route instead of resuming from the route the window was refreshed in. Alternatively we can implement duplicate functionality to dynamically parse the current `window.location` to one of the store routes and trigger the appropriate navigation action with the proper payload. However, ideally this would probably be handled by the library itself by using the existing logic in [getInitialState](https://github.com/faceyspacey/redux-first-router/blob/master/src/reducer/createLocationReducer.js#L43).

If you agree with the potential solution presented above, I can also work on a PR regarding this.

**Comment by ScriptedAlchemy** [comment] 2018-09-10 02:32
What version of RFR are you using
have you tried with the `next` tag on NPM? Theres an update coming which contains a number of fixes

**Comment by woochi** [comment] 2018-09-10 07:26
@ScriptedAlchemy I'm using `0.0.20-next` which should be the latest version available.

**Comment by hedgepigdaniel** [comment] 2018-09-10 09:52
Counter intuitively, the `@rudy` tag is newer than `@next`, despite having a lower version number. You can follow the changes in the "Road to rudy" section in the README.

**Comment by Grsmto** [comment] 2018-09-10 16:15
I confirm this issue with latest version `0.0.9-rudy`.

**Comment by ScriptedAlchemy** [comment] 2018-09-10 20:16
@woochi it might be best to hold off till we release an update which consolidates these tags.

After that, it will be the best time to discuss updates. We are just working on cleaning up a couple things - i want to avoid confusion so that if you open a PR, its to the right version :P

**Comment by hedgepigdaniel** [comment] 2018-09-10 23:55
@woochi If I understand right, you mean to use the `getInitialState` function from within the library to check when adding new routes if it should the current route, and dispatching the new action is necessary?

That seems like a good solution to me. I wonder if the new route action should be a redirect?

I think the two branches you could start from are:
- `rudy` - the latest released version before the rewrite (slightly ahead of `next`). I'm fairly sure you could rebase this kind of change to any of `master`/`next`/`rudy` without too much trouble.
- https://github.com/ScriptedAlchemy/redux-first-router/tree/rudy-respond - the mostly working branch with the rewrite. Its probably worth checking if the issue still exists there, and if the solution still makes sense.

**Comment by ScriptedAlchemy** [comment] 2018-09-11 00:51
Agreed. I would check out my fork and see if the issue is there. Any PR should be made to either `rudy` or https://github.com/ScriptedAlchemy/redux-first-router/tree/rudy-respond

**Comment by ScriptedAlchemy** [comment] 2018-09-17 15:55
@woochi if you need this fixed in the next release, you can submit a PR for it. But I still suggest testing rudy-respond and see if you also need the fix there

**Closed** 2018-10-04 22:01 UTC
