### ISSUE TITLE
[Discussion] Add a 'page' attribute to the RouteObject

### ISSUE THREAD

**Issue by arcdev1** [faceyspacey/redux-first-router#15] opened 2017-06-19 16:20 UTC
It's fairly common that an app will want to load a particular "page" or scene for a given location type. 

This is correctly pointed out in the [Medium article](https://hackernoon.com/pre-release-redux-first-router-a-step-beyond-redux-little-router-cd2716576aea) where the following example is provided:

> Here’s another kind of reducer you’d likely have:
```
const page = (state, action) => {
  switch(action.type) {
    case 'HOME':
       return 'homeScene'
    case 'POST':
       return 'postScene'
    case 'REPOS':
      return 'reposScene'
    case 'REPO':
      return 'repoScene'
    case 'USER':
      return 'userScene'
  }
  
  return state
}
```
> And its corresponding component:
```
const PageComponent = ({ page }) => {
  const Page = pages[page]
  return Page ? <Page /> : null
}
const mapState = ({ page }) => ({ page })
export default connect(mapState)(UserComponent)
// could be a switch (but this is cached):
const pages = {
  homeScene: HomeComponent, 
  postScene: PostComponent,
  reposScene: ReposComponent,
  repoScene: RepoComponent,
  userScene: UserComponent
}
```

What if we just added a `page` attribute to the `RouteObject`? Then we could have:

```
// routes.js

import HomePage from './HomePage.js'
import ContactPage from './ContactPage.js'

const routeMap = {
  HOME: { path: '/', page: HomePage },
  CONTACT: { path: '/', page: ContactPage }
}
```
and:
```
// PageComponent.js

import React from 'react'
import { connect } from 'react-redux'
import routes from './routes'

function mapStateToProps (state) {
  return {
    pathKey: state.location.type
  }
}

const PageComponent = ({ pathKey }) => {
  const Page = routes[pathKey].page
  return <Page />
}

export default connect(mapStateToProps)(PageComponent)

```

Thoughts?

**Comment by eudaimos** [comment] 2017-06-19 16:25
@arcdev1 the way you're trying to use it there may prevent code splitting, but I'm still trying to fully grok that capability so I'm not sure

**Comment by arcdev1** [comment] 2017-06-19 16:45
@eudaimos that's true. We'd need something a little more robust if we want to support code-splitting. Worth thinking about, for sure.

**Comment by arcdev1** [comment] 2017-06-19 17:57
@eudaimos I have a version of this that works with code splitting but it's super ugly. I suppose the point is, it's possible.

So, if we overload the `page` attribute to accept a `string` as well as a Component, we could write a `PageComponent` that looks something like:
```
// PageComponent.js

import React from 'react'
import { connect } from 'react-redux'
import routes from './routes'

function mapStateToProps (state) {
  return {
    pathKey: state.location.type
  }
}

class PageComponent extends React.Component {
  componentWillMount = () => {
    const page = routes[this.props.pathKey].page

    if (typeof page === 'string') {
      // we can't just use a variable below like import(page) because 
      // webpack needs some location info or it croaks.
      import(`../${page}/index.js`).then(asyncPage => {
        this.Component = asyncPage
        this.forceUpdate()
      })
    } else {
      this.Component = page
    }
  };

  render = () => (this.Component ? <this.Component.default /> : null);
}

export default connect(mapStateToProps)(PageComponent)
```

There's probably something more elegant that can be done. Hopefully we can keep the discussion alive.

**Comment by faceyspacey** [comment] 2017-06-20 04:41
Whatup fellas. Nice thread.

I love how you noticed how you can add arbitrary key/vals to your route objects. No changes from the redux-first router are needed to do what you want.

You also could just use the `type` by the way, and maintain a map of types to their component. Or in the code-splitting example's case, a map from types to scenes. That would keep your routesMap cleaner and representative of actual built-in capabilities. My examples where i switched on a scene or had a map of them was just to make it obvious by using a known pattern. *I wouldn't even build a reducer for this since it's not needed :)*

As for the code-splitting thing, just FYI using `import()` without `require.resolveWeak`won't work with SSR. It only works for SPAs. But there's nothing stopping you from using React Loadable or my [React Universal Component](https://github.com/faceyspacey/react-universal-component) package. In fact, there is gonna be direct support for prefetching if ur using that package. 

Also, any day now I'm releasing the async-reactor interface: https://github.com/xtuc/async-reactor

where you can both perform dynamic calls to `import()` and data fetches in the same promise function. You can even call `import()` multiple types. You can also request different things based on props. And that brings us to my main point:

you will be able to do this:

*./components/MyUniversalComponent.js:*
```js
import universal from 'react-universal-component'

const asyncWork = async (props) => {
   const { page, slug } = props
   const data = await Promise.all([import(`./pages/${page}`), fetch(`/post/${slug}`)])

   const Component = data[0].default
   const post = await data[1].json()

   return <Component post={post} />
}

const MyUniversalComponent = universal(asyncWork)
export default MyUniversalComponent
```

*./components/App.js:*
```js
export default () =>
  <div>
    <MyUniversalComponent 
      prefetch 
      page='Post'  
      slug='ssr-splitting-fetching-redux-routing' 
    />

    <div>
        <Link prefetch href='ssr-splitting-fetching-redux-routing' />
        <Link prefetch href='magic-comments' prefetchProps={{ slug, page }} />
        <Link prefetch href='redux-first-router-renamed-rudy' />
    </div>
  </div>
```

...I'm complicating things here since I'm combining 2 concepts: the upcoming react-universal-render package (which helps u resolve combination import()+fetch stateless async components) and redux-first-routing. The former is for a world without redux ultimately. 

When using Redux, the `thunk` route option got you covered. *I just wanted to show off what was to come ;)*

But that said, you can still use React Universal Component the old way--i.e. just for chunk imports. And `<Link prefetch href='rudy' />` will be able to prefetch it just like your thunks or `chunks` you specify in your `route` object. There's a few things I'm trying to work out with it though--namely that if you dynamically import based on a prop. Prefetching must get the `fetchProps` to your async promise function. 

Anyway, I know these thoughts aren't final or fully clear. I just wanted to let you know that there's gonna be first-class support for every angle of code-splitting, which means prefetching is a top priority. Also note: ur thunks will be prefetched as part of prefetching ur chunks. This is about to be deployed (hopefully tonight). So basically u can do all the stuff u can do with Next.js minus the framework. That's one of the primary goals here. And ultimately to do it better with more flexibility, caching, better performance, etc. Ur route objects will get a new `cache` option you can use to provide a function that receives the same state as your `thunk`, so you can produce a cache key from it, and if it's the same, ur thunk won't be executed. It will be assumed u cached the result in redux. U can provide `cache: false` to turn this capability off and manually handle it. And you can not set it, and by default it will hash on the corresponding URL. So if u visit the URL again, the thunk won't be requested, saving u cycles on ur server and tidbits of perf on clients (no need to have ur app doing stuff it already did). 

The challenge is tying this into React Universal Component and React Universal Render before I release it. React Universal Component also has a caching feature based on user-provided cache keys. So I'm playing with creating a global cache (`window.ASYNC_CACHE`) that they both can store hashes in (e.g: { 'some-url': true, 'customKey': true}), and determine if data + imports need to be fetched. Imports will of course only be requested once, since they aren't dynamic like paths with ids and slugs. 

Lastly, this may be of no relevance to you--because as i mentioned Universal Render shines in a world without redux state where developers are requesting data ad-hoc in their components. See, this solution requires a *virtual-dom-only* "pre-render" to resolve all promises recursively (Apollo Does this). After which it renders your app synchronously--this time synchronously and quickly getting ur data from a hash map where it's stored. It's a minor perf thing, but if u can avoid it because ur Redux-First Router's `thunk` capability as shown in the SSR docs, u should. That said, if ur using Apollo, `Universal.render(<App />)` will also work with Apollo. So all bases will be covered.

> ps. you call `Universal.render(<App />)` just like that on the client and server. Whatchu think? Slick huh? There are other args and options of course, but with sensible defaults. For example, just like that, on the client, it will attach ur app to `<div id="root" />`. On the server, it automatically uses [Webpack Flush Chunks](https://github.com/faceyspacey/webpack-flush-chunks) to handle serving your dynamic chunks, using its defaults for chunks named `vendor`, `main` and `bootstrap`. And during development it will create a good-enough string to serve. But of course u can do this:

```js
Universal.render(<App />, ({ app, js, styles, asyncStateJson }) => {
   res.send(
      `<!doctype html>
        <html>
          <head>
            ${styles}
          </head>
          <body>
            <div id="root">${app}</div>
            <script>window.ASYNC_STATE = ${asyncStateJson}</script>
            ${js}
          </body>
        </html>`
    )
  })
}
```

It will have both a high level + low level + mid level usage all covered. But the marketing concept is just `Universal.render()` and not having to deal with all this shit unless u choose to. To me, it has a *ring* to it.

Thoughts are much appreciated. Im on the verge of getting this stuff out and wanna get it right.

**Comment by faceyspacey** [comment] 2017-06-22 11:30
By the way if any of u guys are having success with this package, please do a Medium post to build our community. Developers need to know that this is actually working for people.

Post to r/JavaScript and r/reactjs and echojs.com

I can help if u need an editor

**Comment by faceyspacey** [comment] 2017-07-11 04:23
closing this out. by the way in the latest medium article and codesandbox featured in it I talk a lot about keying into objects to figure out what component to display (as well as do other things like TransitionGroup-based animations, Universal splitting, etc):

https://medium.com/faceyspacey/redux-first-router-lookin-sexy-on-code-sandbox-d9d9bea15053

...as for the idea of adding arbitrary keys on route objects, in the full-featured demo now has a auth filtering based on this exact technique. There's a `role` key added to the `ADMIN` route here:

https://github.com/faceyspacey/redux-first-router-demo/blob/master/src/routesMap.js#L51

The `isAllowed` function here completes the thought:

https://github.com/faceyspacey/redux-first-router-demo/blob/master/src/utils.js#L14

**Closed by faceyspacey** 2017-07-11 04:23 UTC

**Comment by corydeppen** [comment] 2017-09-22 04:39
> ...as for the idea of adding arbitrary keys on route objects, in the full-featured demo now has a auth filtering based on this exact technique. There's a role key added to the ADMIN route

I believe this would suggest the [Flow](https://github.com/faceyspacey/redux-first-router/blob/master/src/flow-types.js#L8) and [TypeScript](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/redux-first-router/index.d.ts#L25) definitions for `RouteObject` need to be tweaked to include an indexer/ index signature property to allow for properties like `role`.

As an aside, is it worth revisiting the idea of maintaining TS definitions in this repo instead of in the DefinitelyTyped repo? DT just seems to add unnecessary friction from both publisher and consumer perspectives. I've been noticing a few inconsistencies in the TS definitions while working with the demo app and I would think posting issues in this repo would give the library author and others an opportunity to read and comment on them and might be easier than remembering to tag specific folks in issues submitted in the DT repo.

/cc @valbrand @viggyfresh

**Comment by faceyspacey** [comment] 2017-09-22 10:34
I'd be open to having it here. Need to get Rudy out first. Then let's revisit it. 

As for the arbitrary keys and typing, I assume you want to parameterize the route type so it can receive info of the types of keys it can have. Sounds great.

**Comment by viggyfresh** [comment] 2017-09-22 16:01
👍 happy to help with upkeep of typings here; I think waiting on Rudy makes sense, as the `next` branch is currently decently covered by the stale typings on DefinitelyTyped (although some things, like `confirmLeave`, are missing).

**Comment by corydeppen** [comment] 2017-09-22 16:30
Although it looks like Flow allows for members to have a different type from the indexer property, TypeScript requires that [all explicit members must also conform to that index signature](https://basarat.gitbooks.io/typescript/docs/types/index-signatures.html#all-members-must-conform-to-the-string-index-signature). The TS constraint makes sense, though - _"...to provide safety so that any string access gives the same result."_

As an alternative, would it be reasonable to use a `meta` or similar type of property bag on `RouteObject` that could have a `[key: string]: string` definition and allow for the arbitrary string values for keys like page, role, etc.?

**Comment by faceyspacey** [comment] 2017-09-22 16:40
I'm not a fan of additional nesting

**Comment by corydeppen** [comment] 2017-09-22 17:06
The following should allow arbitrary keys to be included when defining the route map and prevent a TS error related to properties that don't exist in type `Route`:

```ts
export interface RouteObject {
  // ...
  [key: string]:
    | string
    | boolean
    | RouteThunk
    | ((p: string, k?: string) => string)
    | undefined;
}
```

Since it needs to include the signature for all members, it would just need to be updated as the `RouteObject` definition changes. Small price to pay for type safety.

**Comment by faceyspacey** [comment] 2017-09-23 02:59
oh, i was wondering what the problem is. 

cuz i was thinking we do it like this: `connectRoutes<{ foo: string, bar: number }>()`

and then merge the types of those keys with the built-in keys for routes.

So basically the user just provides the types of any additional keys they want to have on their routes.

**Comment by faceyspacey** [comment] 2017-09-28 13:20
oh my bad, i thought Flow had gotten support for type parameters during call-time like TS. That won't work. It conveys the idea, so perhaps there is something closer we can do in Flow.

**Comment by corydeppen** [comment] 2017-10-17 00:17
I've modified the TS declaration file to include the pattern you mentioned. It seems to work and allows for the custom keys to be provided when the route map is defined.

```ts
// index.d.ts
export type RouteObject<TKeys> = TKeys & {
  capitalizedWords?: boolean;
  navKey?: string;
  path: string;
  thunk?: RouteThunk;
  fromPath?(path: string, key?: string): string;
  toPath?(param: string, key?: string): string;
};

export type Route<TKeys = {}> = RouteString | RouteObject<TKeys>;

export interface RoutesMap<TKeys = {}> {
  [key: string]: Route<TKeys>;
}

// routesMap.ts
const map: RoutesMap<{ role?: string }> = {
  ADMIN: {
    path: '/admin',
    // No longer get error "Object literal may only specify known properties,
    // and 'role' does not exist in type 'Route'."
    role: 'admin',
  },
};
```

The only caveat is that the RoutesMap generic type would need to contain all possible custom keys across the different routes.

**Comment by faceyspacey** [comment] 2017-10-17 02:04
excellent! ...i wonder if this is ever gonna come to Flow, or if it's somehow an impossibility. I'm a flow guy and this is the one thing TS had that I really wish was in Flow.
